version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - service-networks
    volumes:
      - "mongo-data:/data/db"
    expose:
      - ${MONGO_PORT}
    command: mongod
networks:
  service-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"