version: '3.9'

services:
  cassandra:
    image: bitnami/cassandra:latest
    restart: always
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=${TPN}
      - CASSANDRA_CQL_PORT_NUMBER=${CQL_PORT}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
    volumes:
      - data:/data/db
    expose:
      - ${CQL_PORT}
      - ${TPN}
    ports:
      - ${CQL_PORT}:${CQL_PORT}
volumes:
  data:
    driver: local