version: '3.9'

services:
  mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
        - mongo-data:/data/db1
      restart: always
      ports:
        - ${MONGO_PORT}:${MONGO_PORT}
      expose:
        - ${MONGO_PORT}
      networks:
        - mongoCluster
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
networks:
  mongoCluster:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"