version: '3.9'

services:
  envoy:
      image: envoyproxy/envoy-dev:v1.26-latest
      volumes:
        - ./envoy.yaml:/etc/envoy/envoy.yaml
      ports:
        - "8888:8888"
        - "8080:8080"
  mongo1:
      image: mongo:latest
      container_name: mongo1
      volumes:
        - mongo-data:/data/db1
      command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
      restart: always
      ports:
        - ${MONGO_PORT}:${MONGO_PORT}
      expose:
        - ${MONGO_PORT}
      networks:
        - mongoCluster
  mongo2:
      image: mongo:latest
      container_name: mongo2
      command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
      restart: always
      volumes:
        - mongo-data:/data/db2
      ports:
        - ${MONGO_PORT_SECOND}:${MONGO_PORT}
      expose:
        - ${MONGO_PORT_SECOND}
      networks:
        - mongoCluster
  mongo3:
      image: mongo:latest
      container_name: mongo3
      command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
      restart: always
      volumes:
        - mongo-data:/data/db3
      ports:
        - ${MONGO_PORT_THIRD}:${MONGO_PORT}
      expose:
        - ${MONGO_PORT_THIRD}
      networks:
        - mongoCluster
networks:
  mongoCluster:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"